project:
  type: website

website:
  title: "Seismic Exploration Methods"
  sidebar:
    background: primary
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://flexie.github.io/EAS-8803-FH/
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus 
      - href: goals.qmd
        text: Goals
      - href: outline.qmd
        text: Outline                
      - href: schedule.qmd
        text: Schedule
      - href: assignments.qmd
        text: Assignments        
      - href: seminar.qmd
        text: Seminar        
      - href: project.qmd
        text: Final Project 
      - href: references.qmd  
format:
  html:
    theme: cosmo
   # css: styles.css
    toc: true

bibliography: references.bib
license: CC BY



